//! Persistence for Totem memory: the SurrealDB schema, its migrations, and
//! repositories that enforce the store's invariants rather than trusting their
//! callers to.
//!
//! Three properties are load-bearing, and each is enforced here rather than
//! above here (`arrive/systems/058-totem-core/components/store.yaml`):
//!
//! - **Scope isolation.** Every read and write takes a
//!   [`ScopeChain`](totem_core::ScopeChain), and the scope predicate is
//!   generated by this crate. There is no public path to the SurrealDB
//!   connection, so no caller can express a query that omits the filter.
//! - **Append-only episodic history.** Refusing revision in Rust is not enough:
//!   a database `EVENT` refuses `UPDATE` and `DELETE` on episodic rows, so even
//!   a hand-written statement inside this crate cannot rewrite the audit
//!   substrate.
//! - **Provenance on every write.** The schema types `provenance` as a required
//!   object with required members, so a row without an author, harness,
//!   session, and timestamp is refused by the database.
//!
//! Authorization is entirely this crate's job. Per
//! [TD-011](../../../docs/tech-direction/surrealdb.md), a restricted SurrealDB
//! system user is not a row filter — it reads every scope, and its writes are
//! discarded *silently* — so the store connects as a fully-privileged user and
//! never delegates isolation to database roles.
//!
//! ```no_run
//! use totem_core::{ActorId, RepoId, ScopeChain};
//! use totem_store::{RecallQuery, Store};
//!
//! # async fn example() -> Result<(), Box<dyn std::error::Error>> {
//! let store = Store::in_memory().await?;
//! store.migrate().await?;
//!
//! let ada = ActorId::new("ada")?;
//! let repo = RepoId::new("srswart/totem")?;
//! let reader = ScopeChain::resolve(&ada, Some(&repo), &[]);
//!
//! // Nothing outside `reader` can come back: the predicate is ours, not the
//! // caller's.
//! let recalled = store.memories().recall(&reader, &RecallQuery::new()).await?;
//! # let _ = recalled;
//! # Ok(())
//! # }
//! ```

#![warn(missing_docs)]

mod access_log;
pub mod corpus;
mod credential;
mod curation;
mod embedding;
mod error;
mod landscape;
mod memory;
mod migrate;
mod promotion;
mod row;
mod schema;
mod store;

pub use access_log::AccessLogRepository;
pub use credential::{CredentialGrantRow, CredentialRepository};
pub use curation::CurationRepository;
#[cfg(feature = "fastembed")]
pub use embedding::fastembed_embedder::FastembedEmbedder;
pub use embedding::{DeterministicEmbedder, Embedder, embed};
pub use error::{StoreError, StoreResult};
pub use landscape::{
    AdvanceArtifact, AdvanceView, ComponentArtifact, ComponentView, LandscapeRepository,
    LandscapeSnapshot, LandscapeView, OwnerArtifact, RepoArtifact, RepoView, SyncRun, SyncSummary,
    SystemArtifact, SystemView,
};
pub use memory::{MemoryRepository, RankExplanation, RecallQuery, ReembedSummary};
pub use migrate::{AppliedMigration, MIGRATIONS, Migration};
pub use promotion::{PromotionOutcome, PromotionRepository};
pub use schema::EMBEDDING_DIMENSIONS;
pub use store::Store;
